### ISSUE TITLE
Introductie voor mij hoe ik teksten/foto's kan toevoegen en bewerken op de website

### ISSUE THREAD

**Issue by blijblijblij** [schooldehofakker/schooldehofakker.nl#12]

**Comment by blijblijblij** [comment]
De eerste editie van deze website ondersteund nog geen teksteditor achtige functionaliteit, dat zou wel moeten kunnen met extra tools. Dat moet eerst nog even verder onderzocht worden, kom ik op terug.

Voor nu kunnen teksten gewoon bij Rogier of Menno aangeleverd worden, en dan verwerken we dat.

**Comment by blijblijblij** [comment]
https://app.forestry.io/sites/etz0bf8ota3sha/#/ geprobeerd, werkt nog niet helemaal zoals verwacht, maar zie ook dat het uploaden naar de ftp server misgaat #21

**Comment by blijblijblij** [comment]
Forestry doet het nu wel:

<img width="1440" alt="Screenshot 2020-02-25 14 38 34" src="https://user-images.githubusercontent.com/1648248/75252249-94420e00-57dc-11ea-9eb2-a7f19f47c529.png">

Wat kleine schoonheidsfoutjes opgelost, binnenkort misschien even samen naar kijken @Menno79 @HansWyn ?!

**Comment by HansWyn** [comment]
Top kan jij mij hier binnenkort introductie geven hoe ik dit kan gebruiken?

**Comment by blijblijblij** [comment]
Ja, prima, ik kan wel een keertje in de avond, geef maar een gil wat uitkomt @HansWyn, morgenavond of die avond erop!?
