### ISSUE TITLE
Wat nieuwe nieuws berichten produceren en mij de mogelijkheid geven daarin teksten te plaatsen

### ISSUE THREAD

**Issue by blijblijblij** [schooldehofakker/schooldehofakker.nl#16]
Zie ook opmerkingen in #12, ik (@blijblijblij) daar nog wat verder uitzoekwerk naar doen.

Btw, Menno en ik kunnen teksten al wel vast op de meer gecompliceerde manier toevoegen, dus schroom niet die alvast toe te voegen...

**Comment by HansWyn** [comment]
Volgens mij is het handig als je berichten uit het hofnieuws gebruikt. bijvoorbeeld deze:
Tafel kleuterklas
De kleuterklas heeft een grotere tafel, die kan meegroeien
naar 12 kleuters. Dank Menno en Inge voor het sponseren
van deze tafel! Deze komt straks in het nieuwe gedeelte
van de klas te staan.

**Comment by HansWyn** [comment]
Inclusief foto

**Comment by blijblijblij** [comment]
:-) 

https://www.schooldehofakker.nl/2020/02/12/Nieuwe-tafel-kleuterklas/ @HansWyn
