### ISSUE TITLE
Open dag aankondigen

### ISSUE THREAD

**Issue by blijblijblij** [schooldehofakker/schooldehofakker.nl#33]
Heb nu vanuit het hofnieuws

<img width="294" alt="Screenshot 2020-03-03 13 30 38" src="https://user-images.githubusercontent.com/1648248/75775922-4173d380-5d53-11ea-95e0-40f4d9ea51df.png">

maar moet hier nog tekst bij @HansWyn ?

**Comment by blijblijblij** [comment]
Heb de zijkant wat meer aandacht gegeven en de banner voor de opendag er aan toegevoegd, voor de volledigheid zou het handig zijn om die banner te laten linken naar een nieuwsbericht die de opendag aankondigd, zo weten mensen gelijk tijd en invulling van de dag, is daar al iets over bekend @HansWyn ?

<img width="1440" alt="Screenshot 2020-03-03 16 01 49" src="https://user-images.githubusercontent.com/1648248/75788372-6cb4ed80-5d68-11ea-9f9a-4ee3c4736175.png">

**Comment by blijblijblij** [comment]
Ik heb ook een link naar een nieuwsbericht aangemaakt, inhoud van vorig jaar gebruikt, kunnen we eventueel bijschaven, maar dan staat het er al wel

**Comment by HansWyn** [comment]
Ja er is al meer bekend, maar ik denk dat het handig is als dit gewoon
gekoppeld wordt aan de poster die Meia maakt.... Met daaronder toelichting
van het programma. Volgende week krijg je een tekst!

Op di 3 mrt. 2020 om 13:31 schreef Rogier Wessel <notifications@github.com>:

**Comment by blijblijblij** [comment]
👍
