### ISSUE TITLE
Klusdag aankondigen?!

### ISSUE THREAD

**Issue by blijblijblij** [schooldehofakker/schooldehofakker.nl#34]
Moeten we ook via de publieke website de klusdag aankondigen, onder het mom van alle hulp is welkom zou dat misschien best de moeite waard kunnen zijn?! @HansWyn

**Comment by HansWyn** [comment]
Nee denk dat we het gewoon voor de school houden

Op di 3 mrt. 2020 om 13:35 schreef Rogier Wessel <notifications@github.com>:

**Comment by blijblijblij** [comment]
👍
