### ISSUE TITLE
Toevoeging van per stukje van de kracht van de hofakker een sprekende foto

### ISSUE THREAD

**Issue by blijblijblij** [schooldehofakker/schooldehofakker.nl#9]
Vraag Rogier: gewoon uit de bestaande serie een paar eruit halen en toevoegne?!

![www schooldehofakker nl_kracht-van-de-hofakker_](https://user-images.githubusercontent.com/1648248/74337503-ad8c9880-4da0-11ea-93c9-fa5d40a74f96.png)

**Comment by HansWyn** [comment]
Ja uit de huidige serie dus inclusief die van Saffloer wat halen lijkt me het handigst aangezien dit goede foto's zijn!

**Comment by blijblijblij** [comment]
Eerste poging:

![www schooldehofakker nl_kracht-van-de-hofakker_](https://user-images.githubusercontent.com/1648248/74373854-8e602c00-4ddd-11ea-8710-9263d18ad408.png)
